ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: ^(templates|static)/.*|\S+\.js$
  - id: check-toml

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.261
  hooks:
  - id: ruff
    args: [--fix]

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.2
  hooks:
  - id: autopep8
    args: [--in-place, --aggressive, --aggressive, --max-line-length=120, '--ignore=E402,E501']

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.8.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
