services:
  static_serve:
    build:
      context: .
      dockerfile: deployment/httpd.dockerfile

  web_app:
    build:
      context: .
      dockerfile: deployment/django.dockerfile
    volumes:
    - SOURCE_IONIZATION_DIR:/opt/data/ionization:ro
    - SOURCE_EMISSION_DIR:/opt/data/emission:ro
    - db:/opt/data/database
    environment:
      PY_ENV: prod
      IONIZATION_DATASET_DIR: /opt/data/ionization
      EMISSION_DATASET_DIR: /opt/data/emission
    stop_signal: sigkill

  nginx_proxy:
    image: nginx:alpine
    volumes:
    - ./deployment/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - 127.0.0.1:8000:80
    depends_on:
    - web_app
    - static_serve
volumes:
  db:
