name: Build Docker Image

on:
  push:
    branches:
    - main

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest-16-cores

    steps:
    - uses: actions/checkout@v3
      name: Checkout repository

    - uses: docker/setup-buildx-action@v2
      name: Set up Docker Buildx

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: tbhaxor
        password: ${{ github.token }}

    - uses: actions/cache@v3
      name: Cache Docker layers
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - uses: docker/build-push-action@v3
      name: Build image and push
      with:
        push: true
        tags: ghcr.io/tbhaxor/astro-data:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      name: Replace proper cache file
