name: Unit Testing

on:
  pull_request:

jobs:
  test_application:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libhdf5-dev libopenmpi-dev openmpi-bin git gcc g++
      name: Configure test environment
    - uses: actions/checkout@v3
      name: Checkout repository
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install poetry
      uses: snok/install-poetry@v1.0.0
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - run: poetry install
      name: Install dependencies
    - run: poetry run ./manage.py test
      name: Run unit test
      # env:
      #   IONIZATION_DATASET_DIR: .data/ionization
      #   EMISSION_DATASET_DIR: .data/emission
